Initial implementation for quarkus codegen flow (backport #7296)
The implementation is an adaptation from Gradle's
[CodeGenWorker](https://github.com/quarkusio/quarkus/blob/8ddf05405d87255d41fa5c77d9c16d76c7f45b32/devtools/gradle/gradle-application-plugin/src/main/java/io/quarkus/gradle/tasks/worker/CodeGenWorker.java)

<img width="1836" height="1015" alt="Screenshot From 2026-06-20
13-42-39"
src="https://github.com/user-attachments/assets/f190a179-046f-4826-bf35-896c41ba3e7a"
/>

- Quarkus codegen (fixes kafka-avro-schema-quickstart)
- artifactGroupId computation in Quarkus Mill init

With the extra avro example running, windows on CI is timing out, so
I've separated the compilation on windows and mac/linux into two, where
on windows only 3 examples are compiled but it does cover code
generation too.

I've noticed on linux example.migration.javalib is not actually running
though on CI, but even locally, it takes about 1 minute to run the
`example.migrating.javalib.6-maven-quarkus.packaged.daemon` while on the
same machine (via [windows-dockur](https://github.com/dockur/windows))
it takes almost 5 minutes.

I started some timeout adjustments on this, but decided to instead add
some dedicated mill compile command and will revisit later with some
scheduled actions to cover all of the examples in all platforms

[Opened issue](https://github.com/com-lihaoyi/mill/issues/7324) for the
future work related to the above

- Dependency resolution problems (missing libraries after dep
resolution, should be investigated separately and possibly need support
from coursier)
- Platform specific dependency issues (grpc code gen is looking for a
missing dependency, I think this needs another investigation and PR to
fix)
```
io.quarkus.bootstrap.prebuild.CodeGenException: Failed to find com.google.protobuf:protoc:linux-x86_64:exe among dependencies
```

cc: @souvlakias partially resolves #7198 ( :heavy_check_mark: avro :x:
grpc)

Backport of pull request: https://github.com/com-lihaoyi/mill/pull/7296

---------

Co-authored-by: Souvlakia <77302709+souvlakias@users.noreply.github.com>