Add the https://github.com/pbassiner/sbt-multi-project-example project to the test resources
Both `./mill main.init.sbt.test` and running `sbt` in the project directory fail with:

```
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
```

This is likely because I am using JDK 21.