Stabilize arrow tests (#4021)
We've been hitting issues with `Error: Cannot find module
'/home/runner/work/mill/mill/out/example/thirdparty/arrow/local/testCached.dest/sandbox/run-2/out/arrow-libs/core/arrow-core/js/test/nodeModulesDir.super/KotlinJsTests.dest/node_modules/mocha/bin/mocha.js'`,
e.g.
https://github.com/com-lihaoyi/mill/actions/runs/11995071624/job/33438002467.
I suspect it's due to race conditions in the parallel calls to `npm
install`s in the same folder. This PR moves the `npm install`s into the
same task to ensure they happen without concurrency