fix BuildInfo generatedSources, it must be a folder
generatedSources must be a folder,
but till now it was a reference to a generated file
This commit fixes this issue.

There are 2 reasons for this fix:
(1) Because generatedSources must be folders by the definition:
Folders containing source files that are generated
(2) If you use intellij IDEA and build your project from the IDE,
building module, which includes BuildInfo plugin, fails saying:

Error:scalac: Error: /home/vitalii/risk42/repo/risk42-workspace2/out/infinity/foundations/buildInfo/dest/BuildInfo.scala does not exist or is not a directory
scala.reflect.internal.FatalError: /home/vitalii/risk42/repo/risk42-workspace2/out/infinity/foundations/buildInfo/dest/BuildInfo.scala does not exist or is not a directory
	at scala.tools.nsc.settings.MutableSettings$OutputDirs.checkDir(MutableSettings.scala:286)
	at scala.tools.nsc.settings.MutableSettings$OutputDirs.add(MutableSettings.scala:276)
	at xsbt.CachedCompiler0.$anonfun$new$1(CompilerInterface.scala:68)
	at xsbt.CachedCompiler0.$anonfun$new$1$adapted(CompilerInterface.scala:66)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at xsbt.CachedCompiler0.<init>(CompilerInterface.scala:66)
	at xsbt.CompilerInterface.newCompiler(CompilerInterface.scala:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    ...