Fix assertions in `MillInitSbtMultiProjectExampleTests` that fail due to commit 768a2b104f97d0275a47b9e0f4e1f492dec647fd, which is uncompleted in commit c819207ff0e8ad7ad81304ba448e07fa00d85629
Somehow this fails in the CI on Linux with JDK 11 but not on my device:

```text
java.lang.AssertionError: assertion failed: task common.test succeeded
```