Fix `main` build and CI (#4958)
Not sure why these dependencies were listed as `compileMvnDeps` rather
than just `mvnDeps`, but that seems to be the cause of the
`java.lang.NoSuchMethodError`s that were plaguing CI since we removed
scalafmt/parallel-collections from the classpath. Hopefully this helps
make things work again

Seems like the `compile` prefix was added in
https://github.com/com-lihaoyi/mill/pull/4162