Clean up mill process in LauncherOldVersionTests to prevent test report failures (#4251)
Previously the leftover running mill processes caused
`action-junit-report` to fail when it tried to walk the
`out\mill-worker-uyUCkqx6lYTWawU0H+fOCWvQ\u8=-1\mill-093bdc52daae5837bacc1b1b565ee261-io`
file in the sandbox directory


Fixes errors such as 

```
Run mikepenz/action-junit-report@v5
📘 Reading input values
📦 Process test results
  Preparing 1 report as configured.
  Error: EACCES: permission denied, lstat 'D:\a\mill\mill\out\integration\feature\launcher-old-versions\fork\test.dest\mill.integration.LauncherVersionTests_0_10\sandbox\run-1\out\mill-worker-uyUCkqx6lYTWawU0H+fOCWvQ\u8=-1\mill-093bdc52daae5837bacc1b1b565ee261-io'
https://github.com/com-lihaoyi/mill/actions/runs/12565326528/job/35029611094