Fixed compilation error in BomModule example (#6161)
The fix resolves the following compile error:
```console
[build.mill-59] [error] 6 │object myBom extends BomModule {
[build.mill-59] [error]   │       ^
[build.mill-59] [error]   │object creation impossible, since def compile: mill.api.Task.Simple[mill.javalib.api.CompilationResult] in trait SemanticDbJavaModule in package mill.javalib is not defined 
[build.mill-59] [error]   │(The class implements abstract override def compile:
[build.mill-59] [error]   │  mill.api.Task.Simple[mill.javalib.api.CompilationResult] in trait BomModule in package mill.javalib but that definition still needs an implementation)
```