Lock around `info`, `warn`, `error,` `debug` logs to avoid interleaving (#6321)
Fixes https://github.com/com-lihaoyi/mill/issues/6318

Tested manually

```
lihaoyi mill$ ./mill -i dist.run example/javalib/basic/4-module-deps/ -i _.compile
8041] dist.run
Multiple root build files found: build.mill.yaml,build.mill, picking build.mill.yaml
build.mill.yaml-40] parseBuildFiles Multiple root build files found: build.mill.yaml,build.mill, picking build.mill.yaml
build.mill.yaml-61] compile compiling 9 Scala sources to out/mill-build/compile.dest/classes ...
build.mill.yaml-61] done compiling
71] bar.compile compiling 1 Java source to out/bar/compile.dest/classes ...
70] foo.compile compiling 1 Java source to out/foo/compile.dest/classes ...
71] [error] bar/src/bar/Bar.java:9:12
71] context.setVariae
71]            ^^^^^^
71] cannot find symbol
71]   symbol:   method setVariae(java.lang.String,java.lang.String)
71]   location: variable context of type org.thymeleaf.context.Context
70] [error] foo/src/foo/Foo.java:14:27
70] bar.Bar
70]                           ^
70] package bar does not exist
70/71, 2 failed] ============================== _.compile ============================== 6s
71] [error] bar.compile javac returned non-zero exit code
70] [error] foo.compile javac returned non-zero exit code
```

Also added an integration test that fails without these changes