Android: Fixes androidMainActivity to only run when there's no passed activity (#6992)
Fixes an issue introduced in https://github.com/com-lihaoyi/mill/pull/6980


```
1/1, 1 FAILED] mill show Jetcaster.tv.androidRun --activity com.example.jetcaster.tv.MainActivity
Error: 1-099] [error] Jetcaster.tv.androidMainActivity No launchable main activity found in the manifest.
```

Runs the androidMainActivity only if it's not passed as an argument,
avoiding the non-existing error

cc: @souvlakias 

Verification:
https://github.com/vaslabs-ltd/compose-samples-with-mill/actions/runs/24177395330
and
https://github.com/vaslabs-ltd/compose-samples-with-mill/actions/runs/24390871608

Also fixes the auto-detection of Android TV android activities

<img width="1909" height="946" alt="Screenshot From 2026-04-14 12-09-09"
src="https://github.com/user-attachments/assets/d7bc4d31-bdae-40ce-8849-86aac342f610"
/>

Pull request: https://github.com/com-lihaoyi/mill/pull/6992