Add code to add the sbt plugin and run the `millInitGenerateProjectTree` sbt task in `SbtBuildGenMain`, create a "scala-seed-project" test project in test resources with `sbt new`, and update `ProjectTreePlugin`
`./mill main.init.sbt.test` fails.

In the sbt launched under the directory "main/init/sbt/test/resources/scala-seed-project" with `sbt -addPluginSbtFile=/.../mill-init.sbt` with the following content, the `tasks` sbt command output doesn't include an added `millInitGenerateProjectTree` task:

```sbt
addSbtPlugin("com.lihaoyi" % "mill-main-init-sbt-sbt-mill-init-generate-project-tree" % "0.1.0-SNAPSHOT" from "file:/.../mill/out/main/init/sbt/sbtPluginResources.dest/sbt-mill-init-generate-project-tree.jar")
```

The following content of "mill-init.sbt" yields the following result:

```sbt
import mill.main.sbt.ProjectTreePlugin

addSbtPlugin("com.lihaoyi" % "mill-main-init-sbt-sbt-mill-init-generate-project-tree" % "0.1.0-SNAPSHOT" from "file:/.../mill/out/main/init/sbt/sbtPluginResources.dest/sbt-mill-init-generate-project-tree.jar")

enablePlugins(ProjectTreePlugin)

lazy val root = (project in file("."))
  .enablePlugins(ProjectTreePlugin)

```

```text
/Users/shreckye/Projects/mill/mill-init.sbt:1: error: not found: object mill
import mill.main.sbt.ProjectTreePlugin
       ^
/Users/shreckye/Projects/mill/mill-init.sbt:8: error: not found: value ProjectTreePlugin
  .enablePlugins(ProjectTreePlugin)
                 ^
sbt.compiler.EvalException: Type error in expression
```

Reviewing the contents of https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/2.3.1/sbt-assembly_2.12_1.0-2.3.1.jar, I see there is an "sbt/sbt.autoplugins" file which has the content:

```
sbtassembly.AssemblyPlugin

```

This probably means that such a file has to be included for an sbt plugin and a plain Mill module doesn't support this.