Better error messages (#6899)
This improves various things when Mill prints exceptions when tasks
throw.

---

Printing the actual underlying exception of [Mill's serialized
exceptions](https://github.com/com-lihaoyi/mill/blob/39794eb4301517ce80b494b26cb8025030f47a0b/core/api/daemon/src/mill/api/daemon/Result.scala#L165-L168):

Before

```text
[error] fatalTaskSerializedEx
  mill.api.daemon.Result$SerializedException: This is a thing exception
```
(`SerializedException` used as exception class name, no stack trace)

After

```text
[error] fatalTaskSerializedEx
foo.ThingException: This is a thing exception
  Foo.thing(Foos.scala:45)
  Foo$.thing$$anon$491(Foos.scala:48)
  Foo$.thing$$anon$490(Foos.scala:51)
  Foo$.thing$$anon$489(Foos.scala:54)
```

---

For made up exceptions which are not Mill's `SerializedException` and
whose stack trace is unrelated to the Mill one (like Scala.js [can
make](https://github.com/scala-js/scala-js/blob/1cb4eec698fb2de71d981e658c034ee2cdca04fb/test-common/src/main/scala/org/scalajs/testing/common/Serializer.scala#L203-L207)),
don't cut their stack trace:

Before

```text
[error] fatalTaskNoSharedStackTrace
build_.package_$$anon$2: foo.ThingException
```
(no stack trace)

After

```text
[error] fatalTaskNoSharedStackTrace
build_.package_$$anon$2: foo.ThingException
  Foo.thing(Foos.scala:45)
  Foo$.thing$$anon$491(Foos.scala:48)
  Foo$.thing$$anon$490(Foos.scala:51)
  Foo$.thing$$anon$489(Foos.scala:54)
```

---

Re-use the suggested class name and message of `Throwable#toString`
rather than `getClass.getName`, useful for some serialized exception
that [Scala.js can
make](https://github.com/scala-js/scala-js/blob/1cb4eec698fb2de71d981e658c034ee2cdca04fb/test-common/src/main/scala/org/scalajs/testing/common/Serializer.scala#L204)
too:

Before
```text
[error] fatalTaskNoSharedStackTrace
build_.package_$$anon$2: foo.ThingException
  Foo.thing(Foos.scala:45)
  Foo$.thing$$anon$491(Foos.scala:48)
  Foo$.thing$$anon$490(Foos.scala:51)
  Foo$.thing$$anon$489(Foos.scala:54)
```

(exception name is the one of an anonymous made-up class, and the
message is the original exception name)

After
```text
[error] fatalTaskNoSharedStackTrace
foo.ThingException: This is a thing exception
  Foo.thing(Foos.scala:45)
  Foo$.thing$$anon$491(Foos.scala:48)
  Foo$.thing$$anon$490(Foos.scala:51)
  Foo$.thing$$anon$489(Foos.scala:54)
```
(exception name and message are the expected ones)