Allow `Cross` module types to be traits for greater regularity and less boilerplate at callsite (#2427)
## What

### Concise Cross-Module Definition

This PR lets you replace the existing cross-module syntax using
`class`es:

```scala
object bar extends Cross[BarModule](scalaVersions:_*)
class BarModule(val crossScalaVersion: String) extends MyCrossScalaModule{
  def moduleDeps = Seq(qux)
}
```

With a new lighter-weight variant:

```scala
object bar extends Cross[BarModule](scalaVersions)
trait BarModule extends MyCrossScalaModule{
  def moduleDeps = Seq(qux)
}
```

Furthermore, passing in the wrong type of keys to `Cross` is now a
compile error, rather than blowing up at runtime with a stacktrace:

```
  java.lang.ExceptionInInitializerError
    mill.define.BasePathTests$.$anonfun$tests$16(BasePathTests.scala:39)
    mill.define.BasePathTests$.checkMillSourcePath$1(BasePathTests.scala:10)
    mill.define.BasePathTests$.$anonfun$tests$15(BasePathTests.scala:39)
  java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
    mill.util.TestGraphs$singleCross$cross$$anonfun$$lessinit$greater$1.apply(TestGraphs.scala:222)
    mill.define.Cross.$anonfun$items$1(Cross.scala:104)
    scala.collection.immutable.List.map(List.scala:250)
    mill.define.Cross.<init>(Cross.scala:92)
    mill.util.TestGraphs$singleCross$cross$.<init>(TestGraphs.scala:222)
    mill.util.TestGraphs$singleCross$cross$.<clinit>(TestGraphs.scala:222)
    mill.define.BasePathTests$.$anonfun$tests$16(BasePathTests.scala:39)
    mill.define.BasePathTests$.checkMillSourcePath$1(BasePathTests.scala:10)
    mill.define.BasePathTests$.$anonfun$tests$15(BasePathTests.scala:39)
```

We get a compile error with a nice position and error message

```scala
[error] /Users/lihaoyi/Github/mill/main/test/src/mill/util/TestGraphs.scala:222:44: type mismatch;
[error]  found   : Int
[error]  required: String
[error]     object cross extends mill.Cross[Cross](210, "211", "212")
[error]                                            ^
[error] one error found
```

We now require that all `Cross[T]` types `T` are traits inheriting from
`Cross.Module[V]`, and expose `crossValue: V` in the body of the traits
for usage. While for one-off cross `trait`s this is just as verbose as
the status quo, the fact that you can hide the `Cross.Module[V]` on some
base traits such as `CrossScalaModule` means that you don't need to
repeat it on ever cross-module you instantiate, which is a big win.

### Improved type safety 

The `Cross` overhaul in this PR also makes it possible to provide static
errors when the cross-type is invalid:

```scala
TestGraphs.scala:235:60: could not find implicit value for evidence parameter of type mill.define.Cross.ToSegments[sun.misc.Unsafe]
[error]     object cross extends mill.Cross[Cross](210.asInstanceOf[sun.misc.Unsafe])
[error]                                                            ^
```

This previously would crash with confusing stack traces at runtime

### Support for non-string Cross Types

Furthermore, you can properly define cross-modules that take other
non-string types as keys:

```scala
  object nonStringCross extends TestUtil.BaseModule {
    object cross extends mill.Cross[Cross](210, 211, 212)
    trait Cross extends Cross.Module[Int] {
      def suffix = T { crossValue }
    }

    object cross2 extends mill.Cross[Cross2](210L, 211L, 212L)
    trait Cross2 extends Cross.Module[Long] {
      override def millSourcePath = super.millSourcePath / crossValue.toString
      def suffix = T { crossValue }
    }
  }
```

Non-string keys were previously half-supported in Mill: you could depend
on these cross-modules in your build, but you could not reference them
from the command line. Now, they work as expected, using the
`Cross.ToSegments` typeclass to convert them to strings that you can
reference from the command line.


### Extensibility

Multi-dimensional cross modules can be created via the `Cross.Module2`
trait:

```scala
object myCross2 extends Cross[MyCrossModule2](("a", 1), ("b", 2))
trait MyCrossModule2 extends Cross.Module2[String, Int] {
  def param1 = T { "Param Value: " + crossValue }
  def param2 = T { "Param Value: " + crossValue2 }
}

```

Cross modules can also be extended piecemeal with additional axes via
`Cross.ArgN`:

```scala
    object myCross extends Cross[MyCrossModule]("a", "b")
    trait MyCrossModule extends Cross.Module[String] {
      def param1 = T { "Param Value: " + crossValue }
    }

    object myCrossExtended extends Cross[MyCrossModuleExtended](("a", 1), ("b", 2))
    trait MyCrossModuleExtended extends MyCrossModule with Cross.Module2[String, Int] {
      def param2 = T{ "Param Value: " + crossValue2 }
    }

    object myCrossExtendedAgain extends Cross[MyCrossModuleExtendedAgain](("a", 1, true), ("b", 2, false))
    trait MyCrossModuleExtendedAgain extends MyCrossModuleExtended with Cross.Module3[String, Int, Boolean] {
      def param3 = T{ "Param Value: " + crossValue3 }
    }
```

So you can easily take a `CrossScalaModule` which is
`Cross.Module[String]`, and mix in another say `Cross.Arg2[String]` if
you want to cross-build it against different versions of some library as
well

## Motivation

1. Reducing the boilerplate necessary to define a cross module: the
`(val crossScalaVersion: String)` binding was always pretty awkward, and
is pure boilerplate since the user ~never ends up referring to the
`crossScalaVersion` value

2. Mill defines modules as `trait`s that get instantiated as `object`s.
`class`es basically never come into the picture, *except* when defining
`Cross[Module]`s. This change lets those use `trait`s too, making the
framework more regular overall.

3. Make cross-module definition somewhat type safe, so we're not
throwing `Any`s into the `Cross` constructor and getting weird
explosions when we pass in a `Seq[String]` forgetting the `: _*`

## Implementation

1. Introduce a new trait `Cross.Module[V] extends mill.define.Module{
def crossValue: V }` that cross-modules can implement to support
trait-based `Cross[T]` definitions.

2. Update the `Cross`/`Cross.Factory` to recognize when the type given
to `Cross[T]` is a `trait` instead of a `class`, and if so swap the
generated code from `new $tpe(..$argTupleValues)` to `new $tpe{ def
crossValue = $v }`

4. Update the built-in cross modules
`CrossScalaModule`/`CrossSbtModule`/`CrossScalaModule.Base` to implement
`Cross[String]` by default, so the user doesn't need to think about
this. Though anyone defining their own cross-trait (as a one-off or as a
re-usable helper) would still need to make sure they extend
`Cross.Module[T]` with the appropriate `T`

5. I took the opportunity to simplify the existing `Cross.Factory`
macros, as well as replacing `mill.define.Ctx.crossInstances` with
`crossValues` to support `CrossScalaVersionRanges` without needing to
jump through hoops in the macro

## Notes

2. Although type-safety is greatly improved, there still is a bit of
sloppiness in `Cross#apply(arg0: Any, args: Any*)`. It should be
possible to improve this using the same macro technique we use in the
`Cross` constructor, but I was hitting issues with Scala 2 macros and
type inference misbehaving for nested Cross modules. For now we can
leave that for future work

3. I expect most code can just use `crossValue` directly. But if anyone
really needs to give it a name (e.g. if they have multiple nested cross
modules and they need to refer to each one's value) it's relatively easy
to go `def myNamedValue = crossValue` and then use `myNamedValue` after
that. If `crossValue` is a tuple, then destructuring via `val
(crossScalaVersion, crossPlayVersion) = crossValue` works as well

4. Doing a hard cut over to the new logic seems like the best option
v.s. keeping various compatibility shims around:
1. If we keep `Cross[T]` unchanged and introduce a new `Cross.Of[T]` for
the new implementation, then people with existing `Cross[T]`s will face
silent misbehavior due to https://github.com/com-lihaoyi/mill/pull/2347
causing sources and test-sources not to get picked up properly
2. If we move the existing `Cross[T]` implementation to `Cross.Old[T]`,
and make the new implementation `Cross[T]`, then this only marginally
reduces migration work (people still need to manually update every
call-site to `Cross.Old`) while greatly increasing complexity (both in
user code may now have two different styles of cross-module floating
around, and in Mill code which needs 3 due to two concrete
implementations + an abstract base class)
3. If we immediately kill the old logic, nobody gets silent misbehavior,
everyone gets a nice compile error on how to upgrade (we can customize
it with detailed instructions), we avoid having multiple cross-module
implementations.


For some reason the `compileError` macro doesn't properly capture the
custom error messages, but if I manually swap back to an old-style cross
module in the test suite it gives me the following error message:

```
[error] /Users/lihaoyi/Github/mill/main/test/src/mill/util/TestGraphs.scala:269:31: 
[error] Cross type MyCross must be trait, not a class. Please change:
[error] 
[error]   class MyCross(scalaVersion: String, platform: String)
[error] 
[error] To:
[error] 
[error]   trait MyCross extends Cross.Module[(String, String)]{
[error]     val (scalaVersion, platform) = crossValue
[error]   }
[error] 
[error] You also no longer use `: _*` when instantiating a cross-module:
[error] 
[error]   Cross[MyCross](values:_*)
[error] 
[error] Instead, you can pass the sequence directly:
[error] 
[error]   Cross[MyCross](values)
[error] 
[error] Note that the `millSourcePath` of cross modules has changed in
[error] Mill 0.11.0, an no longer includes the cross values by default.
[error] If you have `def millSourcePath = super.millSourcePath / os.up`,
[error] you may remove it. If you do not have this definition, you can
[error] preserve the old behavior via `def millSourcePath = super.millSourcePath / crossValue`
[error] 
[error]     object cross extends mill.Cross[MyCross](crossMatrix:_*)
[error]                               ^
[error] two errors found
```

## Testing

1. All existing tests pass, modified to use the new syntax

2. Added `mill.eval.CrossTests.nonStringCross` and
`mill.eval.CrossTests.crossExtension` to exercise those code paths in
the unit test suite

3. Added additional `MacroErrorTests` to ensure that mis-typed cross
keys or invalid cross types raises the appropriate compile error

4. I moved `integration.feature[cross]` to
`example.misc[6-cross-module-axes]`, modified the test to exercise the
non-string cross-key code path w.r.t. CLI invocation, and cross-module
extension code path using `extends Cross.Arg3[T]`